server:
  port: 8080

---
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://localhost:3306/illustrationDB
    password: '@Password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

